# EXTRACT

Extract csv from FiveThirtyEight: https://github.com/fivethirtyeight/data/tree/master/candy-power-ranking

Extract csv from USDA: https://www.ars.usda.gov/northeast-area/beltsville-md-bhnrc/beltsville-human-nutrition-research-center/methods-and-application-of-food-composition-laboratory/mafcl-site-pages/sr11-sr28/

In [2]:
import pandas as pd
#Import csv with matched names
csv_file = "../data/transformed_candy_3.csv"
clean_candy_df = pd.read_csv(csv_file, encoding = 'utf8')

#TRANSFORM: Removed foreign characters from candy_names
clean_candy_df["candy_names"]=clean_candy_df["candy_names"].str.replace("Õ","")
clean_candy_df

,usda_number,candy_names,candy_detail,NDB_No,Water_(g),Energ_Kcal,Protein_(g),Sugar_Tot_(g)
0,6109,CARAMELS,CHOCOLATE-FLAVOR ROLL,19076,6.69,387,1.59,56.32
1,6174,100 Grand,NaN,19144,6.10,468,2.50,51.90
2,6188,3 Musketeers,NaN,19159,5.80,436,2.60,66.89
3,6130,5TH AVENUE CANDY BAR,NaN,19098,2.30,482,8.78,47.19
4,6183,AFTER EIGHT MINTS,NaN,19153,6.30,432,1.67,66.60
...,...,...,...,...,...,...,...,...
129,6144,Twizzlers,NaN,19112,15.00,348,2.56,39.64
130,6191,WHATCHAMACALLIT CANDY BAR,NaN,19162,3.04,494,8.04,48.86
131,6119,WHITE CHOC,NaN,19087,1.30,539,5.87,59.00
132,6205,YORK BITES,NaN,19181,9.09,394,1.78,75.00
133,6123,YORK PEPPERMINT PATTIE,NaN,19091,9.03,384,2.19,63.78

In [3]:
#TRANSFORM: Change columns names
clean_candy_df.rename(columns={"candy_names":"competitorname", "Water_(g)":"water_g", "Protein_(g)":"protein_g", "Sugar_Tot_(g)":"sugar_g", "Energ_Kcal":"energy_kcal", "NDB_No":"ndb_no"}, inplace=True)
clean_candy_df

,usda_number,competitorname,candy_detail,ndb_no,water_g,energy_kcal,protein_g,sugar_g
0,6109,CARAMELS,CHOCOLATE-FLAVOR ROLL,19076,6.69,387,1.59,56.32
1,6174,100 Grand,NaN,19144,6.10,468,2.50,51.90
2,6188,3 Musketeers,NaN,19159,5.80,436,2.60,66.89
3,6130,5TH AVENUE CANDY BAR,NaN,19098,2.30,482,8.78,47.19
4,6183,AFTER EIGHT MINTS,NaN,19153,6.30,432,1.67,66.60
...,...,...,...,...,...,...,...,...
129,6144,Twizzlers,NaN,19112,15.00,348,2.56,39.64
130,6191,WHATCHAMACALLIT CANDY BAR,NaN,19162,3.04,494,8.04,48.86
131,6119,WHITE CHOC,NaN,19087,1.30,539,5.87,59.00
132,6205,YORK BITES,NaN,19181,9.09,394,1.78,75.00
133,6123,YORK PEPPERMINT PATTIE,NaN,19091,9.03,384,2.19,63.78

In [4]:
# Import candy_ranking dataset from FiveThirtyEight
csv_file = "../data/candy-data-cleaned.csv"
candy_rank_df = pd.read_csv(csv_file, encoding = 'utf8')

#TRANSFORM: Remove foreiogn characters
candy_rank_df["competitorname"]=candy_rank_df["competitorname"].str.replace("Õ","")
candy_rank_df

,competitorname,chocolate,fruity,caramel,peanutyalmondy,nougat,crispedricewafer,hard,bar,pluribus,sugarpercent,pricepercent,winpercent,mother_company
0,100 Grand,1,0,1,0,0,1,0,1,0,0.901261,0.860,0.670,Ferrero
1,3 Musketeers,1,0,0,0,1,0,0,1,0,0.445922,0.511,0.676,"Mars, Inc."
2,One dime,0,0,0,0,0,0,0,0,0,-1.663576,0.116,0.323,Unknown
3,One quarter,0,0,0,0,0,0,0,0,0,-1.663576,0.511,0.461,Unknown
4,Air Heads,0,1,0,0,0,0,0,0,0,1.520236,0.511,0.523,Perfetti Van Melle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,Twizzlers,0,1,0,0,0,0,0,0,0,-0.920093,0.116,0.455,Hershey's
81,Warheads,0,1,0,0,0,0,1,0,0,-1.371875,0.116,0.390,Impact Confections
82,Welch's Fruit Snacks,0,1,0,0,0,0,0,0,1,-0.589262,0.313,0.444,Welch Foods Inc.
83,Werther's Original Caramel,0,0,1,0,0,0,1,0,0,-1.041043,0.267,0.419,Storck
84,Whoppers,1,0,0,0,0,1,0,0,1,1.399287,0.848,0.495,Hershey's

In [5]:
#TRANSFORM: Merge datasets on "competitorname" and drop any rows that don't match
merge_candy_df = pd.merge(clean_candy_df, candy_rank_df, on="competitorname", how="inner")
merge_candy_df

,usda_number,competitorname,candy_detail,ndb_no,water_g,energy_kcal,protein_g,sugar_g,chocolate,fruity,...,peanutyalmondy,nougat,crispedricewafer,hard,bar,pluribus,sugarpercent,pricepercent,winpercent,mother_company
0,6174,100 Grand,NaN,19144,6.10,468,2.50,51.90,1,0,...,0,0,1,0,1,0,0.901261,0.860,0.670,Ferrero
1,6188,3 Musketeers,NaN,19159,5.80,436,2.60,66.89,1,0,...,0,1,0,0,1,0,0.445922,0.511,0.676,"Mars, Inc."
2,6101,Almond Joy,NaN,19065,8.20,479,4.13,48.34,1,0,...,1,0,0,0,1,0,-0.048547,0.767,0.503,Hershey's
3,6143,Baby Ruth,NaN,19111,6.99,459,5.40,54.00,1,0,...,1,1,0,0,1,0,0.445922,0.767,0.569,Ferrero
4,6104,Nestle Butterfinger,NaN,19069,1.23,459,5.40,45.90,1,0,...,1,0,0,0,1,0,0.445922,0.767,0.707,Ferrero
5,6141,Kit Kat,NaN,19109,1.63,518,6.51,48.68,1,0,...,0,0,1,0,1,0,-0.589262,0.511,0.768,Hershey's
6,6170,Peanut M&Ms,NaN,19140,2.48,515,9.57,50.75,1,0,...,1,0,0,0,0,1,0.406791,0.651,0.695,Ferrero
7,8599,Milky Way Midnight,NaN,42196,7.20,443,3.20,57.81,1,0,...,0,1,0,0,1,0,0.901261,0.441,0.608,"Mars, Inc."
8,6266,Milky Way,NaN,19256,6.99,463,4.28,58.65,1,0,...,0,1,0,0,1,0,0.445922,0.651,0.731,Hershey's
9,6172,Mounds,NaN,19142,9.05,486,4.60,46.19,1,0,...,0,0,0,0,1,0,-0.589262,0.860,0.478,"Mars, Inc."
10,6173,Mr Good Bar,NaN,19143,0.45,538,10.22,47.22,1,0,...,1,0,0,0,1,0,-0.589262,0.918,0.545,Hershey's
11,6470,Payday,NaN,19923,6.97,490,13.44,40.32,0,0,...,1,1,0,0,1,0,-0.048547,0.767,0.463,Ferrero
12,6182,Rolo,NaN,19152,4.60,474,5.08,63.93,1,0,...,0,0,0,0,0,1,1.356599,0.860,0.657,Sweetworks
13,6341,Skittles original,NaN,19370,3.83,405,0.19,75.84,0,1,...,0,0,0,0,0,1,1.644743,0.220,0.631,Smarties Candy Company
14,6334,Skittles wildberry,NaN,19363,3.83,402,0.19,75.92,0,1,...,0,0,0,0,0,1,1.644743,0.220,0.551,"Mars, Inc."
15,6185,Snickers,NaN,19155,5.55,491,7.53,50.47,1,0,...,1,1,0,0,1,0,0.239597,0.651,0.767,Mondelez International
16,6330,Snickers Crisper,NaN,19359,4.47,488,6.86,46.54,1,0,...,1,0,1,0,1,0,0.445922,0.651,0.595,"Mars, Inc."
17,6186,Starburst,NaN,19156,8.51,408,0.41,58.12,0,1,...,0,0,0,0,0,1,-1.165549,0.220,0.670,Unknown
18,6299,Starburst,NaN,19313,8.51,409,0.41,58.18,0,1,...,0,0,0,0,0,1,-1.165549,0.220,0.670,Unknown
19,6100,Tootsie Roll Juniors,CHOCOLATE-FLAVOR ROLL,19064,6.69,387,1.59,56.32,1,0,...,0,0,0,0,0,0,-0.589262,0.511,0.431,Ferrero
20,6189,Twix,NaN,19160,4.23,502,4.91,48.25,1,0,...,0,0,1,0,1,0,0.239597,0.906,0.816,"Mars, Inc."
21,6144,Twizzlers,NaN,19112,15.00,348,2.56,39.64,0,1,...,0,0,0,0,0,0,-0.920093,0.116,0.455,Hershey's

In [6]:
#TRANSFORM: Drop irrelevant columns
final_candy_df = merge_candy_df[["competitorname", 'ndb_no', 'water_g', 'energy_kcal', 'protein_g', 'sugar_g', "chocolate", "fruity", "caramel", "peanutyalmondy","crispedricewafer","hard","bar", "pluribus", "sugarpercent", "pricepercent","winpercent"]]
final_candy_df

,competitorname,ndb_no,water_g,energy_kcal,protein_g,sugar_g,chocolate,fruity,caramel,peanutyalmondy,crispedricewafer,hard,bar,pluribus,sugarpercent,pricepercent,winpercent
0,100 Grand,19144,6.10,468,2.50,51.90,1,0,1,0,1,0,1,0,0.901261,0.860,0.670
1,3 Musketeers,19159,5.80,436,2.60,66.89,1,0,0,0,0,0,1,0,0.445922,0.511,0.676
2,Almond Joy,19065,8.20,479,4.13,48.34,1,0,0,1,0,0,1,0,-0.048547,0.767,0.503
3,Baby Ruth,19111,6.99,459,5.40,54.00,1,0,1,1,0,0,1,0,0.445922,0.767,0.569
4,Nestle Butterfinger,19069,1.23,459,5.40,45.90,1,0,0,1,0,0,1,0,0.445922,0.767,0.707
5,Kit Kat,19109,1.63,518,6.51,48.68,1,0,0,0,1,0,1,0,-0.589262,0.511,0.768
6,Peanut M&Ms,19140,2.48,515,9.57,50.75,1,0,0,1,0,0,0,1,0.406791,0.651,0.695
7,Milky Way Midnight,42196,7.20,443,3.20,57.81,1,0,1,0,0,0,1,0,0.901261,0.441,0.608
8,Milky Way,19256,6.99,463,4.28,58.65,1,0,1,0,0,0,1,0,0.445922,0.651,0.731
9,Mounds,19142,9.05,486,4.60,46.19,1,0,0,0,0,0,1,0,-0.589262,0.860,0.478
10,Mr Good Bar,19143,0.45,538,10.22,47.22,1,0,0,1,0,0,1,0,-0.589262,0.918,0.545
11,Payday,19923,6.97,490,13.44,40.32,0,0,0,1,0,0,1,0,-0.048547,0.767,0.463
12,Rolo,19152,4.60,474,5.08,63.93,1,0,1,0,0,0,0,1,1.356599,0.860,0.657
13,Skittles original,19370,3.83,405,0.19,75.84,0,1,0,0,0,0,0,1,1.644743,0.220,0.631
14,Skittles wildberry,19363,3.83,402,0.19,75.92,0,1,0,0,0,0,0,1,1.644743,0.220,0.551
15,Snickers,19155,5.55,491,7.53,50.47,1,0,1,1,0,0,1,0,0.239597,0.651,0.767
16,Snickers Crisper,19359,4.47,488,6.86,46.54,1,0,1,1,1,0,1,0,0.445922,0.651,0.595
17,Starburst,19156,8.51,408,0.41,58.12,0,1,0,0,0,0,0,1,-1.165549,0.220,0.670
18,Starburst,19313,8.51,409,0.41,58.18,0,1,0,0,0,0,0,1,-1.165549,0.220,0.670
19,Tootsie Roll Juniors,19064,6.69,387,1.59,56.32,1,0,0,0,0,0,0,0,-0.589262,0.511,0.431
20,Twix,19160,4.23,502,4.91,48.25,1,0,1,0,1,0,1,0,0.239597,0.906,0.816
21,Twizzlers,19112,15.00,348,2.56,39.64,0,1,0,0,0,0,0,0,-0.920093,0.116,0.455

In [7]:
#Drop duplicates
final_candy_df.drop_duplicates(subset ="competitorname", 
                     keep ='first', inplace = True)
final_candy_df

/var/folders/3r/pv_sqnpd6bb8wr1nhrml1snw0000gq/T/ipykernel_41208/889005483.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_candy_df.drop_duplicates(subset ="competitorname",

,competitorname,ndb_no,water_g,energy_kcal,protein_g,sugar_g,chocolate,fruity,caramel,peanutyalmondy,crispedricewafer,hard,bar,pluribus,sugarpercent,pricepercent,winpercent
0,100 Grand,19144,6.10,468,2.50,51.90,1,0,1,0,1,0,1,0,0.901261,0.860,0.670
1,3 Musketeers,19159,5.80,436,2.60,66.89,1,0,0,0,0,0,1,0,0.445922,0.511,0.676
2,Almond Joy,19065,8.20,479,4.13,48.34,1,0,0,1,0,0,1,0,-0.048547,0.767,0.503
3,Baby Ruth,19111,6.99,459,5.40,54.00,1,0,1,1,0,0,1,0,0.445922,0.767,0.569
4,Nestle Butterfinger,19069,1.23,459,5.40,45.90,1,0,0,1,0,0,1,0,0.445922,0.767,0.707
5,Kit Kat,19109,1.63,518,6.51,48.68,1,0,0,0,1,0,1,0,-0.589262,0.511,0.768
6,Peanut M&Ms,19140,2.48,515,9.57,50.75,1,0,0,1,0,0,0,1,0.406791,0.651,0.695
7,Milky Way Midnight,42196,7.20,443,3.20,57.81,1,0,1,0,0,0,1,0,0.901261,0.441,0.608
8,Milky Way,19256,6.99,463,4.28,58.65,1,0,1,0,0,0,1,0,0.445922,0.651,0.731
9,Mounds,19142,9.05,486,4.60,46.19,1,0,0,0,0,0,1,0,-0.589262,0.860,0.478
10,Mr Good Bar,19143,0.45,538,10.22,47.22,1,0,0,1,0,0,1,0,-0.589262,0.918,0.545
11,Payday,19923,6.97,490,13.44,40.32,0,0,0,1,0,0,1,0,-0.048547,0.767,0.463
12,Rolo,19152,4.60,474,5.08,63.93,1,0,1,0,0,0,0,1,1.356599,0.860,0.657
13,Skittles original,19370,3.83,405,0.19,75.84,0,1,0,0,0,0,0,1,1.644743,0.220,0.631
14,Skittles wildberry,19363,3.83,402,0.19,75.92,0,1,0,0,0,0,0,1,1.644743,0.220,0.551
15,Snickers,19155,5.55,491,7.53,50.47,1,0,1,1,0,0,1,0,0.239597,0.651,0.767
16,Snickers Crisper,19359,4.47,488,6.86,46.54,1,0,1,1,1,0,1,0,0.445922,0.651,0.595
17,Starburst,19156,8.51,408,0.41,58.12,0,1,0,0,0,0,0,1,-1.165549,0.220,0.670
19,Tootsie Roll Juniors,19064,6.69,387,1.59,56.32,1,0,0,0,0,0,0,0,-0.589262,0.511,0.431
20,Twix,19160,4.23,502,4.91,48.25,1,0,1,0,1,0,1,0,0.239597,0.906,0.816
21,Twizzlers,19112,15.00,348,2.56,39.64,0,1,0,0,0,0,0,0,-0.920093,0.116,0.455